export const MIN_TEXT_CONTENTS_LENGTH = 20
export const MAX_TEXT_CONTENTS_LENGTH = 1000

export const MAX_DISPLAYED_TAG_COUNT = 3
export const MAX_SEARCH_WORD_LENGTH = 20

export const MAX_SEARCH_TAG_LENGTH = 40
